import HomePage from "@/components/HomePage";
import Head from "next/head";
import { useEffect, useState } from "react";
import Image from "next/image";
import Product from "@/components/Product";

interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  picture: string;
}

export default function Home() {
  const [productsInfo, setProductsInfo] = useState<Product[]>([]);
  const [phrase,setPhrase] = useState('');


  useEffect(() => {
    fetch('/api/products')
      .then(response => response.json())
      .then((json: Product[]) => setProductsInfo(json));
  }, []);

  const categoriesNames = Array.from(new Set(productsInfo.map(p => p.category)));

  console.log(categoriesNames)

  let products: Product[] = [];
  if (phrase) {
    products = productsInfo.filter(p => p.name.toLowerCase().includes(phrase.toLowerCase()));
  } else {
    products = productsInfo;
  }
  
  return (
    <>
      <Head>
        <title>Ecommerce App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" type="image/jpg" href=""/>
      </Head>
      <div className="w-full justify-center items-center mx-16">
      <div className="bg-gray-100">
        <div className="w-full mx-auto py-6 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold text-gray-900">Welcome to our store!</h1>
        </div>
        
        <div>
        <input value={phrase} onChange={e => setPhrase(e.target.value)} type="text" placeholder="Search for products..." className="bg-gray-200 w-full py-2 px-4 rounded-xl"/>
      {categoriesNames.map(categoryName => (
          <div key={categoryName}>
            {products.find(p => p.category === categoryName) && (
              <div>
                <h2 className="text-2xl capitalize py-5">{categoryName}</h2>
            <div className="grid md:flex">
            {products.filter(p => p.category === categoryName).map(product =>(
              // <div>{product.name}</div>
              <div className="px-6">
              <Product
              key={product.id}
              id={product.id}
              name={product.name}
              description={product.description}
              price={product.price}
              category={product.category}
              picture={product.picture}
                                    />
                  </div>
              ))}
              </div>
              </div>
              )}
  
          </div>
        ))}
        
</div>


        {/* <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8 grid gap-6 grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
          {productInfo.map((product) => (
            <div key={product.id} className="bg-white overflow-hidden shadow-md sm:rounded-lg">
              <div className="relative h-48 w-full">
                <Image
                  src={product.picture}
                  alt={`Picture of ${product.name}`}
                  layout="fill"
                  objectFit="contain"
                />
              </div>
              <div className="px-4 py-5 sm:p-6">
                <h3 className="text-lg font-medium leading-6 text-gray-900">{product.name}</h3>
                <p className="mt-2 max-w-2xl text-sm text-gray-500">{product.description}</p>
                <p className="mt-2 max-w-2xl text-lg font-bold text-gray-900">${product.price}</p>
              </div>
            </div>
          ))}
        </div> */}
      </div>
      </div>
    </>
  );
}