import Head from "next/head";
import Image from "next/image";
import { useRouter } from 'next/router';
import { useContext, useState, useEffect } from "react";
import axios from "axios";
import { CartContext } from "@/components/CartContext";
import Layout from "@/components/Layout";

interface Product {
    _id: string;
    name: string;
    description: string;
    price: number;
    category: string;
    picture: string;
}

export default function CartPage() {
    const {selectedProducts, addProduct, removeProduct} = useContext(CartContext);
    const [products, setProducts] = useState<Product[]>([]);
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [city, setCity] = useState('');
    const [postalCode, setPostalCode] = useState('');
    const [streetAddress, setStreetAddress] = useState('');
    const [country, setCountry] = useState('');
    const router = useRouter();
    const {success, canceled} = router.query;

    useEffect(() => {
        if (selectedProducts.length > 0) {
            axios.post('/api/cart', {ids:selectedProducts})
            .then(response => {
                setProducts(response.data);
            })
        } else {
            setProducts([]);
        }
    }, [selectedProducts]);

    function addMore(id: string) {
        addProduct(id);
    }

    function addLess(id: string) {
        removeProduct(id);
    }

    async function goToPayment() {
        const response = await axios.post('/api/checkout', {
        name,email,city,postalCode,streetAddress,country,
        selectedProducts,
        });
        if (response.data.url) {
        window.location = response.data.url;
        }
    }

    let total = 0;
        for (const _id of selectedProducts) {
            const price = products.find(p => p._id === _id)?.price || 0;
            total += price;
    }

    if (success) {
        return (
        <Layout>
            <div className="grid text-center justify-center items-center mt-28">
            <h1 className="text-2xl text-green-500 mb-10">Thanks for your order!</h1>
            <p className="text-2xl text-green-500">We will email you when your order will be sent.</p>
            </div>
        </Layout>
        );
    }
        
    if (canceled) {
        return (
        <Layout>
            <div className="grid text-center justify-center items-center mt-28">
            <h1 className="text-2xl text-red-500 mb-10">Payment canceled!</h1>
            <p className="text-2xl text-red-500">Your payment has not been processed. Try again.</p>
            </div>
        </Layout>
        );
    }

    return (
        <>
            <Head>
            <title>Ecommerce App | Cart</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" type="image/jpg" href=""/>
            </Head>
            <Layout>
        <div className="w-full bg-white h-full justify-center items-center mt-6">
        <div className="flex justify-center ml-0 md:justify-start md:ml-32">
            <p className="text-2xl md:text-3xl xl:text-4xl text-indigo-400 font-bold mt-8 mb-8 md:mb-0">Your Cart</p>
        </div>
            <div className="grid md:grid-cols-2">
            <div className="flex justify-center items-center">
            {!selectedProducts?.length && (
            <h1 className="text-xl font-medium mt-10 text-center text-red-500">Your cart is empty!</h1>)}
    {products && products.length > 0 && (
    <table className="w-80 mx-auto">
    <thead>
    
    <tr className="text-indigo-400">
        <th className="flex">Product</th>
        <th className="w-1/3">Quantity</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
        {products.map((product: Product) => (
        <tr key={product._id}>
            <td className="text-gray-500 font-bold">{product.name}
                <Image src={product.picture} alt="product photo" className="object-contain max-h-full max-w-full mb-3" width={150} height={100} />
                </td>
            <td>
                <button 
                onClick={() => addLess(product._id)}
                className="bg-indigo-400 text-white w-6 h-6 rounded-lg mr-2">-</button>
            {selectedProducts.filter(id => id === product._id).length}
                <button 
                onClick={() => addMore(product._id)}
                className="bg-indigo-400 text-white w-6 h-6 rounded-lg ml-2">+</button>
            </td>
            <td className="font-medium text-gray-400">
            {selectedProducts.filter(id => id === product._id).length * product.price}$
            </td>
            </tr>  
            ))}
            <tr className="font-bold">
                <td></td>
                <td className="text-gray-400">Total</td>
                <td className="text-indigo-400">{total}$</td>
                </tr>
            </tbody>
            </table>
        )}
        </div>
        {!!selectedProducts.length && (
        <div className="flex justify-center items-center mx-auto w-full mt-16 md:mt-0">
            <div className="flex flex-col text-indigo-400">
            <p className="text-2xl md:text-3xl xl:text-4xl text-center font-bold">Order information</p>
            <div className="flex flex-col mt-5 w-80 mx-auto">
            <input 
            type="text" 
            placeholder="Name"
            value={name}
            name="name"
            onChange={ev => setName(ev.target.value)} 
            className="border-2 py-2 my-1 p-2 rounded-xl focus:outline-none focus:border-indigo-300 focus:placeholder-indigo-300"
            required/>
            <input 
            type="email" 
            placeholder="Email"
            value={email}
            name="email"
            onChange={ev => setEmail(ev.target.value)}
            className="border-2 py-2 my-1 p-2 rounded-xl focus:outline-none focus:border-indigo-300 focus:placeholder-indigo-300"
            required/>
            <div className="flex">
            <input 
            type="text" 
            placeholder="City"
            value={city}
            name="city"
            onChange={ev => setCity(ev.target.value)}
            className="border-2 py-2 my-1 p-2 rounded-xl mr-4 w-40 focus:outline-none focus:border-indigo-300 focus:placeholder-indigo-300"
            required/>
            <input 
            type="text" 
            placeholder="Postal Code"
            value={postalCode}
            name="postalcode"
            onChange={ev => setPostalCode(ev.target.value)}
            className="border-2 py-2 my-1 p-2 rounded-xl w-36 focus:outline-none focus:border-indigo-300 focus:placeholder-indigo-300"
            required/>
            </div>
            <input 
            type="text" 
            placeholder="Street Address"
            value={streetAddress}
            name="address"
            onChange={ev => setStreetAddress(ev.target.value)}
            className="border-2 py-2 my-1 p-2 rounded-xl focus:outline-none focus:border-indigo-300 focus:placeholder-indigo-300"
            required/>
            <input 
            type="text" 
            placeholder="Country"
            value={country}
            name="country"
            onChange={ev => setCountry(ev.target.value)}
            className="border-2 py-2 my-1 p-2 rounded-xl focus:outline-none focus:border-indigo-300 focus:placeholder-indigo-300"
            required/>
            </div>
            <div className="mt-6 bg-indigo-400 border-2 rounded-md flex justify-center items-center w-52 mx-auto text-white font-medium">
            <button
            onClick={goToPayment}>Continue to payment</button>
            </div>
            </div>
            </div>
            )}
        </div>
        </div>
        </Layout>
        </>
    );
};