import HomePage from "@/components/HomePage";
import Head from "next/head";
import { useEffect, useState } from "react";
import Image from "next/image";
import Product from "@/components/Product";
import { initMongoose } from "@/lib/mongoose";
import { findAllProducts } from "./api/products";
import Navbar from '@/components/Navbar'

interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  picture: string;
}

interface HomeProps {
  products: Product[];
}

export default function Home({ products }: HomeProps) {
  const [phrase, setPhrase] = useState<string>('');

  const categoriesNames = Array.from(new Set(products.map(p => p.category)));

  let filteredProducts = products;

  if (phrase) {
    filteredProducts = products.filter(p => p.name.toLowerCase().includes(phrase.toLowerCase()));
  }

  return (
    <>
      <Head>
        <title>Ecommerce App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" type="image/jpg" href=""/>
      </Head>
      <Navbar/>
      <div className="w-full justify-center items-center mx-16 mt-20">
      <div className="bg-gray-100">
        <div className="w-full mx-auto py-6 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold text-gray-900">Welcome to our store!</h1>
        </div>
        
        <div>
        <input value={phrase} onChange={e => setPhrase(e.target.value)} type="text" placeholder="Search for products..." className="bg-gray-200 w-full py-2 px-4 rounded-xl"/>
      {categoriesNames.map(categoryName => (
          <div key={categoryName}>
            {filteredProducts.find(p => p.category === categoryName) && (
              <div>
                <h2 className="text-2xl capitalize py-5">{categoryName}</h2>
            <div className="grid md:flex">
            {filteredProducts.filter(p => p.category === categoryName).map(product =>(
              // <div>{product.name}</div>
              <div className="px-6" key={product.name}>
              <Product
              key={product.id}
              id={product.id}
              name={product.name}
              description={product.description}
              price={product.price}
              category={product.category}
              picture={product.picture}
                                    />
                  </div>
              ))}
              </div>
              </div>
              )}
          </div>
        ))}
      </div>
      </div>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  await initMongoose();
  const products = await findAllProducts();
  return {
    props: {
      products: JSON.parse(JSON.stringify(products)),
    },
  };
}
