import Head from "next/head";
import { useEffect, useState } from "react";
import Product from "@/components/Product";
import Layout from "@/components/Layout";

interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  category: string;
  picture: string;
}

export default function Home() {
  const [productsInfo, setProductsInfo] = useState<Product[]>([]);
  const [phrase,setPhrase] = useState('');

  useEffect(() => {
    fetch('/api/products')
      .then(response => response.json())
      .then((json: Product[]) => setProductsInfo(json));
  }, []);

  const categoriesNames = Array.from(new Set(productsInfo.map(p => p.category)));

  let products: Product[] = [];
  if (phrase) {
    products = productsInfo.filter(p => p.name.toLowerCase().includes(phrase.toLowerCase()));
  } else {
    products = productsInfo;
  }
  
  return (
    <>
      <Head>
        <title>Ecommerce App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" type="image/jpg" href=""/>
      </Head>
      <Layout>
      <div className="w-full justify-center items-center mx-16">
      <div className="bg-gray-100">
        <div className="w-full mx-auto py-6 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold text-gray-900">Welcome to our store!</h1>
        </div>
        
        <div>
        <input value={phrase} onChange={e => setPhrase(e.target.value)} type="text" placeholder="Search for products..." className="bg-gray-200 w-full py-2 px-4 rounded-xl"/>
      {categoriesNames.map(categoryName => (
          <div key={categoryName}>
            {products.find(p => p.category === categoryName) && (
              <div>
                <h2 className="text-2xl capitalize py-5">{categoryName}</h2>
            <div className="grid md:flex">
            {products.filter(p => p.category === categoryName).map(product =>(
              <div className="px-6" key={product.name}>
              <Product
              key={product.id}
              _id={product.id}
              name={product.name}
              description={product.description}
              price={product.price}
              category={product.category}
              picture={product.picture}
                                    />
                  </div>
              ))}
              </div>
              </div>
              )}
          </div>
        ))}
</div>
      </div>
      </div>
      </Layout>
    </>
  );
}